# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hashing.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rhashing.proto\x12\nfile_store\x1a\x1bgoogle/protobuf/empty.proto\"U\n\x0ePutFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x15\n\rfile_contents\x18\x02 \x01(\x0c\x12\x1a\n\x12replication_factor\x18\x03 \x01(\x05\"\"\n\x0eGetFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"(\n\x0fGetFileResponse\x12\x15\n\rfile_contents\x18\x01 \x01(\x0c\x32\x8e\x01\n\tFileStore\x12=\n\x07PutFile\x12\x1a.file_store.PutFileRequest\x1a\x16.google.protobuf.Empty\x12\x42\n\x07GetFile\x12\x1a.file_store.GetFileRequest\x1a\x1b.file_store.GetFileResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hashing_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PUTFILEREQUEST._serialized_start=58
  _PUTFILEREQUEST._serialized_end=143
  _GETFILEREQUEST._serialized_start=145
  _GETFILEREQUEST._serialized_end=179
  _GETFILERESPONSE._serialized_start=181
  _GETFILERESPONSE._serialized_end=221
  _FILESTORE._serialized_start=224
  _FILESTORE._serialized_end=366
# @@protoc_insertion_point(module_scope)
